version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: api-db
    restart: always
    tty: true
    ports:
      - '3302:3306'
    volumes:
      - .docker/dbdata:/var/lib/mybase
    environment:
      - MYSQL_ROOT_PASSWORD=docker456
      - MYSQL_DATABASE=projectdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=docker123
